[project]
name = "lrutility"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "pyexiv2>=2.15.4",
]

[dependency-groups]
test = [
    "pytest",
] 

lint = [
    "mypy~=1.17.0",
    "ruff~=0.12.0",
    "mdformat==0.7.21",
    "mdformat-footnote==0.1.1",
    "mdformat-frontmatter==2.0.8",
    "mdformat-gfm==0.4.1",
]

[tool.uv]
default-groups = ["test", "lint"]
